<a href="https://colab.research.google.com/github/axviolyn/Data-Mining/blob/main/Praktikum3Normalisasi_DM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np
 from sklearn.preprocessing import MinMaxScaler

 #Data contoh(ganti dengan data anda)
 data = np.array([[2.0, 5.0],
               [1.0, 4.0],
               [3.0, 6.0]])

# Inisialisai objek MinMaxScaler
scaler = MinMaxScaler()

# Fit dan transformasi data menggunakan min-max scaling
scaled_data = scaler.fit_transform(data)

print("Data asli:")
print(data)

print("\nData setelah Min-Max Scaling:")
print(scaled_data)


Data asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Min-Max Scaling:
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]


In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Data contoh
data = np.array([[2.0, 5.0],
                 [1.0, 4.0],
                 [3.0, 6.0]])

# Inisialisai objek standarscaler
scaler = StandardScaler()

# Fit dan transformasi data menggunakan min-max scaling
z_score_data = scaler.fit_transform(data)

print("Data asli:")
print(data)

print("\nData setelah Z-Score Transformation:")
print(z_score_data)

Data asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Z-Score Transformation:
[[ 0.          0.        ]
 [-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]]


In [3]:
import numpy as np

# data contoh
data = np.array([200, 300, 400, 500, 600])

# Menentukan faktor penggeseran (scaling factor),
# Misalnya 1000 untuk mengubah ke tentang 0-1
scaling_factor = 1000

# Melakukan transformasi decimal scaling
scaled_data = data / scaling_factor

print("Data asli:")
print(data)

print("\nData setelah scaling:")
print(scaled_data)


Data asli:
[200 300 400 500 600]

Data setelah scaling:
[0.2 0.3 0.4 0.5 0.6]
